# Generated by Django 5.0.4 on 2025-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Descripcion', models.CharField(max_length=50)),
                ('NumHoras', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
