# Generated by Django 5.2 on 2025-04-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTuNota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='NumHoras',
            new_name='numHoras',
        ),
    ]
