# Generated by Django 5.2 on 2025-04-27 21:10

import AppGestionAcademica.models.curso
import AppGestionAcademica.models.nota
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('numero_horas', models.IntegerField(validators=[AppGestionAcademica.models.curso.validateNumeroHoras])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('tipo', models.CharField(choices=[('Quiz', 'Quiz'), ('Trabajo', 'Trabajo'), ('Parcial', 'Parcial')], max_length=10, verbose_name='tipo')),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='AppGestionAcademica.curso')),
            ],
            options={
                'db_table': 'examenes',
                'unique_together': {('curso', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[AppGestionAcademica.models.nota.validateValorNota])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='AppGestionAcademica.examen')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
