# Generated by Django 5.2 on 2025-04-27 00:59

import AppGestionAcademica.models.curso
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero_horas',
            field=models.IntegerField(validators=[AppGestionAcademica.models.curso.validateNumeroHoras]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tipo',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Trabajo', 'Trabajo'), ('Parcial', 'Parcial')], max_length=10, verbose_name='tipo'),
        ),
    ]
