# Generated by Django 5.2 on 2025-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionAcademica', '0002_alter_curso_descripcion_alter_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
