# Generated by Django 5.2 on 2025-04-27 02:44

import AppGestionAcademica.models.nota
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionAcademica', '0003_alter_examen_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='titulo',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[AppGestionAcademica.models.nota.validateValorNota]),
        ),
    ]
